nodeLinker: node-modules
yarnPath: .yarn/releases/yarn-3.2.1.cjs
logFilters:
  - level: discard
    code: YN0062
  - level: discard
    code: YN0063
  - level: discard
    code: YN0002
  - level: discard
    code: YN0060
